In [1]:
from imports.ASLDataset import ASLDataset
import torch
#torch.set_default_dtype(torch.float32) 

l = ASLDataset(letters=['a', 'b'], overwrite_processing=True, train_val_test='train')

RecursionError: maximum recursion depth exceeded while calling a Python object

In [ ]:
n = len(dataset)
data_train, data_test = torch.utils.data.random_split(
    dataset, 
    [int(n*0.8), int(n*0.2)], 
    generator=torch.Generator().manual_seed(42)
)

In [133]:
from 

In [128]:
out

NameError: name 'out' is not defined

In [6]:
from pathlib import Path
import shutil
from tqdm.auto import tqdm
import numpy as np

def random_split(x, prop=[0.80, 0.1, 0.1]):
    assert sum(prop) == 1, "sum of prop must be 1"
    n = len(x)
    np.random.shuffle(x)
    
    train_idx = int(prop[0]*n) 
    val_idx = train_idx + int(prop[1]*n) 
    out = np.split(x, [train_idx, val_idx])
    return {'train': out[0], 'val': out[1], 'test': out[2]}
    
zpad = lambda x, n: str(x).zfill(n)

np.random.seed(0)
letters = ['a']
datadir = Path("/home/hussain/data/event_based_sign_lang/")
new_dir = datadir.parent / 'event_based_sign_lang'
for letter in letters:
    split = random_split(np.arange(1, 4201))
    for key, part in split.items():
        for i, idx in enumerate(tqdm(part, desc=f'{letter}_{key}')):
            raw = datadir / 'raw' / letter / f'{letter}_{str(idx).zfill(4)}.mat'
            proc = datadir / 'processed' / letter / f'{letter}_{str(idx).zfill(4)}.pt'
            
            shutil.move(raw, new_dir / key / 'raw' / letter / f'{letter}_{zpad(i, 4)}.mat')
            shutil.move(proc, new_dir / key / 'processed' / letter / f'{letter}_{zpad(i, 4)}.pt')

a_train:   0%|          | 0/3360 [00:00<?, ?it/s]

a_val:   0%|          | 0/420 [00:00<?, ?it/s]

a_test:   0%|          | 0/420 [00:00<?, ?it/s]

In [126]:
glob.glob(f"/home/hussain/data/event_based_sign_lang/{letters}/a/a_0001.*")

[]

In [109]:
3360 + 420*2

4200

In [55]:
from sklearn.model_selection import train_test_split

train, val, test = train_test_split(range(1, 4201))

ValueError: not enough values to unpack (expected 3, got 2)

In [42]:
from imports.sample_io import load_sample
from imports.utils import make_graph

a = load_sample('a', sample_id=222)
g = make_graph(a)
g

Data(x=[2730], pos=[2730, 3], num_nodes=2730, edge_index=[2, 61551], edge_attr=[61551, 3])

a_vs_b.ipynb	 imports		 __pycache__	   run.py
data		 log			 requirements.txt  slurm.sh
environment.yml  network_analysis.ipynb  results	   testing


In [48]:
test = [3049, 6887, 3106, 3924, 5302, 3480, 2584, 1873, 4922, 6800, 5240, 564, 2903, 6039, 1464, 2107, 5998, 4429, 1199, 7953, 2273, 6345, 2617, 346, 2888, 5452, 8320, 6891, 20, 2813, 530, 1478, 2922, 6402, 4854, 4692, 1708, 5137, 5189, 551, 6660, 6133, 1614, 182, 5770, 4622, 75, 6299, 889, 6857, 4157, 669, 1647, 2049, 4852, 1102, 1600, 2910, 4260, 1584, 5366, 5362, 2261, 8085, 5731, 3481, 5288, 7338, 3085, 1696, 6161, 7763, 6629, 975, 1966, 8004, 3471, 3730, 3222, 7281, 3602, 7180, 7249, 4499, 7103, 2238, 6696, 6275, 3877, 2062, 7971, 6495, 4179, 4770, 3512, 6011, 5503, 5194, 5345, 3186, 6414, 2090, 4935, 3663, 803, 8177, 478, 7327, 3094, 7384, 6922, 6195, 148, 8371, 4695, 6031, 767, 8337, 6180, 728, 2006, 3533, 1590, 4094, 8083, 8135, 3321, 1033, 3945, 6132, 6928, 1436, 1080, 3415, 7265, 966, 7724, 969, 1880, 7094, 860, 5468, 515, 3013, 251, 1860, 7714, 942, 8305, 8234, 5344, 3497, 2896, 558, 1117, 8126, 7439, 2624, 2499, 972, 8390, 750, 3, 3757, 887, 1811, 7784, 1904, 7811, 1625, 289, 4044, 4009, 1959, 1025, 3182, 1249, 2136, 4817, 4305, 4941, 1194, 6913, 7584, 1492, 4522, 4163, 6967, 6904, 6855, 7500, 1828, 8228, 5507, 1429, 7092, 4147, 3142, 7164, 397, 2859, 1694, 1728, 3465, 1755, 2638, 5083, 1045, 5097, 3034, 1699, 3725, 2051, 7922, 6589, 6611, 3388, 533, 2298, 6806, 2962, 2189, 5340, 6424, 4878, 3089, 6466, 992, 4015, 1713, 5863, 1263, 4287, 5709, 340, 1344, 4901, 7642, 572, 7371, 861, 7000, 2339, 1313, 4185, 7358, 1623, 3608, 218, 5748, 2736, 674, 4640, 2458, 2997, 5115, 6403, 5433, 2073, 6996, 4805, 4159, 6297, 4166, 2418, 5579, 2727, 5967, 2215, 946, 4136, 7108, 7036, 3737, 6295, 8334, 1526, 3408, 6907, 6843, 4124, 5134, 5055, 5784, 6715, 7643, 7395, 4943, 2580, 2616, 6337, 114, 6134, 1939, 7995, 2091, 806, 2547, 3614, 5019, 5203, 8288, 2214, 3275, 1620, 2806, 7376, 6241, 8123, 7942, 4690, 6395, 4336, 6983, 3721, 6250, 1751, 3547, 7881, 4508, 6819, 372, 5310, 4745, 5227, 3470, 4535, 7966, 762, 2231, 763, 7370, 4977, 3117, 6964, 8221, 694, 3859, 1356, 7234, 2067, 1806, 7843, 8312, 962, 5074, 7599, 6511, 8333, 1982, 2971, 2286, 3910, 1709, 6995, 2301, 5650, 5873, 4524, 2218, 5589, 7021, 8081, 5876, 4644, 5725, 974, 2324, 7278, 1646, 3261, 4898, 2634, 4757, 22, 1825, 3197, 6539, 568, 6574, 5457, 1394, 5436, 5101, 1520, 677, 5733, 6557, 773, 7446, 7800, 5518, 4191, 3709, 7341, 5405, 2945, 3157, 3110, 691, 6038, 4297, 8192, 4842, 6197, 1026, 7221, 6191, 953, 8235, 4518, 6316, 2123, 6004, 5525, 4701, 1189, 6422, 5411, 1543, 8066, 2391, 173, 2363, 4171, 5114, 8104, 3744, 3876, 4950, 5237, 7837, 5081, 3054, 6346, 2087, 2745, 6591, 2546, 1975, 7755, 4478, 5195, 1264, 1425, 3184, 7728, 7519, 6597, 1761, 7884, 5122, 2244, 310, 787, 3983, 6260, 2296, 238, 2486, 1164, 808, 552, 5230, 8034, 8105, 231, 4417, 4421, 5304, 3994, 3304, 4214, 4894, 2721, 7211, 3414, 1248, 1519, 5553, 3954, 2185, 2881, 3684, 3345, 4763, 8329, 6760, 2647, 6710, 6230, 6072, 2316, 4334, 7156, 2722, 224, 1913, 6681, 8106, 7751, 8087, 3871, 6610, 4804, 5485, 1131, 2994, 7962, 1016, 2493, 2656, 1032, 7540, 2728, 1322, 5771, 1474, 4754, 494, 1457, 7682, 2907, 4762, 3968, 5239, 5341, 3819, 3291, 4645, 209, 5819, 2130, 3203, 8028, 3883, 7305, 7680, 5167, 5372, 6795, 807, 3485, 5837, 3324, 3987, 1012, 7264, 6971, 7241, 520, 5141, 118, 5530, 8188, 1764, 2824, 8074, 5021, 6669, 2715, 1010, 3147, 7992, 1522, 7677, 3962, 2639, 2431, 5406, 5927, 1914, 2987, 4399, 3548, 5427, 5823, 7037, 6571, 6054, 1850, 4959, 6664, 2475, 2227, 4960, 6818, 2216, 146, 2689, 5202, 3574, 5073, 5275, 3206, 4463, 7367, 3088, 8082, 3048, 2427, 3099, 2471, 5197, 3466, 7597, 1134, 766, 6573, 5955, 178, 5076, 986, 5647, 7227, 5668, 3544, 4698, 1450, 5401, 411, 3041, 321, 6434, 5611, 8316, 7125, 1316, 3451, 1273, 6630, 5907, 1341, 7835, 5325, 3816, 2355, 8303, 5674, 8068, 7152, 3352, 4850, 3330, 6029, 1226, 5383, 670, 3557, 7432, 1212, 1407, 7910, 5078, 8009, 7505, 2953, 464, 7239, 4507, 841, 1663, 4670, 3761, 599, 7936, 4732, 5455, 4261, 7423, 1789, 4806, 565, 2726, 7359, 6044, 8262, 4746, 7303, 4855, 2913, 2671, 3459, 1768, 4080, 1517, 8343, 5763, 6752, 3580, 4065, 3031, 1604, 7742, 2074, 2995, 3234, 7631, 5161, 7437, 7287, 5922, 1943, 2253, 2266, 7210, 2540, 7577, 3072, 5691, 3255, 160, 7482, 7059, 4031, 259, 542, 6328, 4982, 3853, 1533, 4315, 2930, 7067, 4575, 8397, 4378, 2618, 1068, 510, 3916, 7805, 4318, 5154, 3438, 977, 8271, 1210, 4224, 2852, 3201, 472, 5702, 5852, 6503, 5815, 4218, 6836, 441, 3650, 7284, 5481, 5279, 1855, 7485, 1793, 832, 2205, 4234, 6502, 537, 4587, 2654, 3439, 7569, 8002, 4740, 5333, 4052, 4388, 7055, 6410, 6109, 5919, 4739, 414, 3340, 4840, 8368, 4477, 6192, 5459, 5632, 1929, 6731, 3163, 2857, 8001, 3995, 169, 5100, 7679, 2151, 7464, 7935, 5317, 4905, 2785, 7110, 2128, 6118, 4643, 4230, 830, 6820, 6184, 869, 7004, 4212, 5196, 6112, 2289, 6366, 3784, 6358, 5734, 3381, 93, 6081, 7841, 5803, 3153, 3432, 7725, 1949, 6238, 7828, 2108, 633, 8258, 4295, 3656, 5754, 3242, 2406, 3549, 571, 6734, 4702, 3285, 6634, 6430, 4720, 1732, 2422, 7315, 1648, 1627, 1652, 5257, 3204, 7262, 753, 1389, 7257, 4896, 7417, 7877, 344, 3192, 5379, 3446, 1542, 316, 3573, 6190, 225, 6602, 7379, 6274, 7427, 7009, 4245, 6642, 6768, 6662, 7917, 7836, 7237, 7419, 2739, 1790, 3960, 7990, 33, 3595, 1148, 6355, 4759, 4150, 8344, 1444, 827, 6898, 608, 7226, 1136, 1231, 6087, 4096, 8287, 5569, 8246, 7559, 1094, 2609, 5667, 3862, 3413, 6565, 2305, 1127, 2284, 6485, 6024, 6546, 2378, 6123, 8291, 4904, 1958, 1129, 1236, 6101, 7770, 213, 1552, 7980, 7509, 7997, 2604, 8256, 2054, 5604, 2762, 369, 3467, 5617, 8011, 3584, 6838, 5966, 6618, 286, 5884, 2300, 5854, 6621, 5251, 6884, 4231, 3159, 5677, 4856, 7039, 1595, 6108, 7850, 1480, 7788, 4131, 4008, 2312, 4001, 3456, 2254, 6169, 926, 4331, 8031, 8131, 5628, 3788, 4566, 501, 4976, 761, 32, 8174, 2666, 2402, 6858, 3959, 1863, 4262, 7629, 4837, 3937, 31, 5282, 302, 3931, 285, 41, 1208, 5059, 1166, 7952, 7560, 1902, 8159, 3621, 4722, 4581, 3511, 795, 4501, 1572, 7296, 6243, 4921, 7711, 4387, 3504, 7295, 1716, 3500, 5540, 7889, 2364, 7978, 4035, 3407, 5680, 1445, 6335, 4607, 3272, 3835, 5376, 4801, 3047, 3339, 2650, 1495, 8171, 6512, 4682, 7068, 3745, 6147, 2777, 1037, 7960, 7916, 4814, 2690, 4310, 3478, 5567, 5956, 7455, 5562, 7717, 208, 7006, 6921, 7167, 2120, 7698, 7012, 4207, 7430, 5838, 3988, 4003, 915, 5243, 2376, 4436, 4973, 4676, 5351, 8097, 699, 1822, 5653, 3605, 2667, 6878, 836, 2573, 3810, 5663, 1591, 3935, 477, 4046, 693, 3703, 293, 5749, 4393, 1501, 309, 7888, 652, 5058, 287, 5736, 1800, 8187, 3689, 3824, 5746, 4591, 8194, 1779, 2291, 1083, 957, 1839, 5408, 8244, 5874, 495, 7635, 4627, 7674, 6389, 5853, 5679, 5517, 5117, 1427, 3037, 2918, 7771, 3524, 4626, 6139, 1363, 2131, 6105, 5834, 2800, 337, 5659, 8166, 5200, 7261, 627, 7254, 7172, 5226, 92, 6876, 2879, 8374, 176, 7040, 4957, 7269, 3629, 7596, 3746, 6528, 2441, 3990, 5545, 5041, 930, 4738, 6315, 7204, 8307, 2225, 1490, 5550, 3042, 1292, 339, 1541, 1011, 2714, 602, 6013, 404, 4380, 3280, 4781, 1674, 1848, 3193, 1295, 1354, 4074, 698, 5781, 868, 80, 5088, 2776, 4120, 539, 7866, 1844, 935, 23, 575, 1891, 7157, 6849, 6198, 2442, 8090, 759, 2725, 5184, 5421, 1774, 4917, 3091, 2664, 4771, 5397, 2691, 6055, 2293, 823, 3015, 7339, 6370, 5685, 7143, 4798, 2880, 1162, 5949, 2564, 5508, 1976, 8062, 7267, 1396, 4314, 4151, 7175, 6686, 1757, 256, 3364, 7945, 4831, 4010, 5319, 1698, 4910, 7387, 72, 5986, 216, 3226, 4951, 6684, 4386, 56, 1645, 3850, 5171, 2641, 7421, 5132, 4784, 2612, 2229, 802, 2730, 2070, 3566, 3248, 6067, 6301, 4435, 2008, 4232, 7064, 1169, 6947, 765, 7169, 5213, 3095, 1838, 5070, 1952, 6089, 1392, 4317, 192, 3694, 2141, 6255, 1448, 7601, 6645, 2700, 5645, 7138, 7715, 2278, 3832, 3634, 6266, 4500, 6832, 7766, 6777, 4146, 2415, 4240, 4221, 7733, 7566, 7613, 4934, 6853, 1485, 2199, 5217, 8226, 2874, 7512, 7831, 4703, 2033, 5844, 3144, 2057, 7116, 2177, 150, 2179, 5204, 2076, 2640, 2494, 5566, 991, 306, 6361, 6667, 2125, 4178, 6725, 2524, 850, 2840, 7535, 1220, 7294, 952, 2037, 8248, 6341, 6778, 3768, 4747, 4758, 2876, 457, 3838, 2743, 7849, 4999, 1214, 7532, 5735, 5571, 1072, 2709, 3140, 779, 7778, 3129, 5936, 6976, 7361, 4526, 5394, 5729, 7658, 2428, 3443, 4126, 5474, 734, 6314, 5858, 8036, 1953, 5516, 2754, 4183, 7819, 5353, 498, 86, 6877, 4860, 4186, 1613, 3922, 3997, 7390, 6615, 6614, 3194, 6692, 7176, 3173, 629, 3368, 2050, 2154, 1615, 5003, 2955, 5942, 8071, 876, 8006, 1554, 4423, 7651, 4674, 7302, 5280, 5607, 4753, 8088, 7982, 1227, 2533, 4091, 2864, 2525, 427, 7489, 1925, 8379, 2371, 5045, 2345, 1217, 1282, 2899, 838, 3063, 7862, 307, 512, 5527, 6900, 1679, 7927, 8150, 2319, 610, 1955, 4641, 6639, 4748, 2465, 1230, 3719, 1715, 1380, 1228, 2140, 6620, 2946, 319, 7905, 4827, 6185, 2251, 1511, 3847, 2235, 5168, 2466, 188, 7533, 2322, 5219, 7248, 4345, 7429, 1758, 7034, 1351, 1672, 6352, 5028, 6130, 85, 6334, 3882, 3825, 4455, 3299, 5390, 951, 1536, 6086, 7511, 2644, 1664, 5361, 6745, 6063, 4404, 6592, 7277, 2592, 6239, 3776, 2648, 4034, 5712, 4558, 1632, 5346, 7406, 7418, 1184, 749, 4284, 5994, 6600, 4116, 5036, 3115, 7695, 1798, 3929, 8284, 7744, 4254, 5892, 3264, 5818, 8046, 531, 4793, 1857, 6215, 5833, 3578, 2670, 4079, 7897, 3593, 4691, 904, 1369, 8339, 2758, 5909, 583, 2166, 4932, 4275, 8151, 5000, 3540, 1144, 872, 5245, 7752, 2608, 973, 8115, 1951, 4446, 7579, 5013, 1500, 7091, 5872, 6014, 5543, 5449, 144, 706, 4012, 6647, 2948, 6077, 3236, 152, 97, 1776, 7968, 90, 2041, 4502, 1887, 1229, 7514, 4972, 4223, 4123, 2157, 3926, 1463, 2587, 1938, 6333, 6599, 4830, 8245, 1243, 6283, 7173, 7785, 943, 2702, 2933, 2032, 4177, 4538, 5943, 2082, 1049, 2815, 5812, 6496, 4868, 2449, 6977, 3421, 5697, 4648, 2887, 2202, 116, 522, 1079, 4985, 1297, 3113, 4603, 1137, 2208, 5029, 3138, 6972, 4853, 4411, 4114, 2109, 956, 7286, 7567, 1753, 6478, 4704, 6464, 3726, 1245, 8300, 8195, 6300, 7057, 815, 3673, 2021, 1234, 768, 5062, 3923, 5082, 6814, 345, 3554, 665, 1053, 4956]

In [49]:
for i in test

[3049,
 6887,
 3106,
 3924,
 5302,
 3480,
 2584,
 1873,
 4922,
 6800,
 5240,
 564,
 2903,
 6039,
 1464,
 2107,
 5998,
 4429,
 1199,
 7953,
 2273,
 6345,
 2617,
 346,
 2888,
 5452,
 8320,
 6891,
 20,
 2813,
 530,
 1478,
 2922,
 6402,
 4854,
 4692,
 1708,
 5137,
 5189,
 551,
 6660,
 6133,
 1614,
 182,
 5770,
 4622,
 75,
 6299,
 889,
 6857,
 4157,
 669,
 1647,
 2049,
 4852,
 1102,
 1600,
 2910,
 4260,
 1584,
 5366,
 5362,
 2261,
 8085,
 5731,
 3481,
 5288,
 7338,
 3085,
 1696,
 6161,
 7763,
 6629,
 975,
 1966,
 8004,
 3471,
 3730,
 3222,
 7281,
 3602,
 7180,
 7249,
 4499,
 7103,
 2238,
 6696,
 6275,
 3877,
 2062,
 7971,
 6495,
 4179,
 4770,
 3512,
 6011,
 5503,
 5194,
 5345,
 3186,
 6414,
 2090,
 4935,
 3663,
 803,
 8177,
 478,
 7327,
 3094,
 7384,
 6922,
 6195,
 148,
 8371,
 4695,
 6031,
 767,
 8337,
 6180,
 728,
 2006,
 3533,
 1590,
 4094,
 8083,
 8135,
 3321,
 1033,
 3945,
 6132,
 6928,
 1436,
 1080,
 3415,
 7265,
 966,
 7724,
 969,
 1880,
 7094,
 860,
 5468,
 515,
 3013,
 251,
 1860,


In [46]:
n = len(l)
data_train, data_test = torch.utils.data.random_split(
    l, 
    [int(n*0.8), int(n*0.2)], 
    generator=torch.Generator().manual_seed(42)
)

In [47]:
data_train

In [3]:
from imports.NVSModel import ResGNet, og_Net, Net

model = Net(2).to('cuda')
model

Net(
  (conv_blocks): ModuleDict(
    (conv_block1): ConvBlock(
      (conv): SplineConv(1, 64, dim=3)
      (bn): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (conv_block2): ConvBlock(
      (conv): SplineConv(64, 128, dim=3)
      (bn): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (conv_block3): ConvBlock(
      (conv): SplineConv(128, 256, dim=3)
      (bn): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (conv_block4): ConvBlock(
      (conv): SplineConv(256, 512, dim=3)
      (bn): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (pool_blocks): ModuleDict(
    (pool_block1): MaxPooling(voxel_size=20)
    (pool_block2): MaxPooling(voxel_size=30)
    (pool_block3): MaxPooling(voxel_size=50)
    (pool_block4): MaxPoolingX(voxel_size=80, size=64)
  )
  (fc1): Linear(in_features=32768, out_features=1024, bias=T

In [4]:
from torch_geometric.loader import DataLoader

dl = DataLoader(l, 3, shuffle=True)

In [5]:
batch = next(iter(dl)).to('cuda')

In [6]:
model(batch)

tensor([[-0.7028, -0.6836],
        [-0.6094, -0.7846],
        [-0.6874, -0.6989]], device='cuda:0', grad_fn=<LogSoftmaxBackward0>)

In [24]:
from torchmetrics import Accuracy

Acc=Accuracy()


In [16]:
batch.y

tensor([1, 1, 0], device='cuda:0')

In [33]:
import torch.nn.functional as F


def train(epoch, train_loader):
    model.train()

    if epoch == 60:
        for param_group in optimizer.param_groups:
            param_group['lr'] = 0.0001

    if epoch == 110:
        for param_group in optimizer.param_groups:
            param_group['lr'] = 0.00001

    for i, data in enumerate(tqdm(train_loader, desc='batches')):
        with torch.autograd.detect_anomaly():
            data = data.to('cuda')
            #print(data.y)
            optimizer.zero_grad()
            end_point = model(data)
            
            loss = F.nll_loss(end_point, data.y)
            pred = end_point.max(1)[1]
            
            acc = (pred.eq(data.y).sum().item())/len(data.y)
            
            loss.backward()
            optimizer.step()
            
            if i % 5 == 0:
                print(data.y, pred, Acc(data.y.to('cpu'), pred.to('cpu')))
                print({'epoch': epoch,'batch': i + 1,'loss': loss.item(),'acc': acc})
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [29]:
"" 

''

In [34]:
model.train()

Net(
  (conv_blocks): ModuleDict(
    (conv_block1): ConvBlock(
      (conv): SplineConv(1, 64, dim=3)
      (bn): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (conv_block2): ConvBlock(
      (conv): SplineConv(64, 128, dim=3)
      (bn): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (conv_block3): ConvBlock(
      (conv): SplineConv(128, 256, dim=3)
      (bn): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (conv_block4): ConvBlock(
      (conv): SplineConv(256, 512, dim=3)
      (bn): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (pool_blocks): ModuleDict(
    (pool_block1): MaxPooling(voxel_size=20)
    (pool_block2): MaxPooling(voxel_size=30)
    (pool_block3): MaxPooling(voxel_size=50)
    (pool_block4): MaxPoolingX(voxel_size=80, size=64)
  )
  (fc1): Linear(in_features=32768, out_features=1024, bias=T

In [35]:
from tqdm.auto import tqdm


for epoch in range(1, 2):
    
    #train_data_aug = T.Compose([T.Cartesian(cat=False), T.RandomFlip(axis=0, p=0.3), T.RandomScale([0.95,0.999]), T.RandomFlip(axis=1, p=0.2)])
    train_loader = dl
    
    train(epoch, train_loader)

batches:   0%|          | 0/2800 [00:00<?, ?it/s]

/tmp/ipykernel_14667/634645094.py:16: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():


tensor([0, 1, 0], device='cuda:0') tensor([0, 1, 0], device='cuda:0') tensor(1.)
{'epoch': 1, 'batch': 1, 'loss': 0.23057891428470612, 'acc': 1.0}
tensor([0, 0, 1], device='cuda:0') tensor([1, 1, 0], device='cuda:0') tensor(0.)
{'epoch': 1, 'batch': 6, 'loss': 6.120129108428955, 'acc': 0.0}
tensor([0, 1, 1], device='cuda:0') tensor([0, 1, 0], device='cuda:0') tensor(0.6667)
{'epoch': 1, 'batch': 11, 'loss': 0.28697383403778076, 'acc': 0.6666666666666666}
tensor([1, 1, 1], device='cuda:0') tensor([1, 1, 0], device='cuda:0') tensor(0.6667)
{'epoch': 1, 'batch': 16, 'loss': 0.23637212812900543, 'acc': 0.6666666666666666}
tensor([0, 1, 0], device='cuda:0') tensor([1, 1, 0], device='cuda:0') tensor(0.6667)
{'epoch': 1, 'batch': 21, 'loss': 6.32385778427124, 'acc': 0.6666666666666666}
tensor([0, 0, 1], device='cuda:0') tensor([0, 1, 0], device='cuda:0') tensor(0.3333)
{'epoch': 1, 'batch': 26, 'loss': 2.0908076763153076, 'acc': 0.3333333333333333}
tensor([1, 0, 0], device='cuda:0') tensor([1

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 3000 but got size 2999 for tensor number 1 in the list.

In [ ]:
import torch
model = torch.load('model.pkl')
model

In [ ]:
import pandas as pd

log = pd.read_csv('log', names = ['epoch', 'batch', 'loss', 'acc'])
log

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns


plt.plot(log['loss'])

In [ ]:
sns.lineplot(x=log.index, y=log['loss'], )

In [ ]:
from imports.NVSModel import Net

model = Net(
    n_classes=2
    #layer_sizes=[64, 128],
    #voxel_sizes=[4, 6]
)
model

In [ ]:
model.fc1

In [ ]:
512*64